var searchData=
[
  ['serializable_268',['Serializable',['../structsupermap_1_1io_1_1Serializable.html',1,'supermap::io']]],
  ['serializable_3c_20false_20_3e_269',['Serializable&lt; false &gt;',['../structsupermap_1_1io_1_1Serializable.html',1,'supermap::io']]],
  ['serializable_3c_20true_20_3e_270',['Serializable&lt; true &gt;',['../structsupermap_1_1io_1_1Serializable.html',1,'supermap::io']]],
  ['serializehelper_271',['SerializeHelper',['../structsupermap_1_1io_1_1SerializeHelper.html',1,'supermap::io']]],
  ['serializehelper_3c_20bytearray_3c_20len_20_3e_20_3e_272',['SerializeHelper&lt; ByteArray&lt; Len &gt; &gt;',['../structsupermap_1_1io_1_1SerializeHelper_3_01ByteArray_3_01Len_01_4_01_4.html',1,'supermap::io']]],
  ['serializehelper_3c_20key_3c_20keylen_20_3e_20_3e_273',['SerializeHelper&lt; Key&lt; KeyLen &gt; &gt;',['../structsupermap_1_1io_1_1SerializeHelper_3_01Key_3_01KeyLen_01_4_01_4.html',1,'supermap::io']]],
  ['serializehelper_3c_20keyvalue_3c_20key_2c_20value_20_3e_20_3e_274',['SerializeHelper&lt; KeyValue&lt; Key, Value &gt; &gt;',['../structsupermap_1_1io_1_1SerializeHelper_3_01KeyValue_3_01Key_00_01Value_01_4_01_4.html',1,'supermap::io']]],
  ['serializehelper_3c_20mayberemovedvalue_3c_20t_20_3e_20_3e_275',['SerializeHelper&lt; MaybeRemovedValue&lt; T &gt; &gt;',['../structsupermap_1_1io_1_1SerializeHelper_3_01MaybeRemovedValue_3_01T_01_4_01_4.html',1,'supermap::io']]],
  ['serializehelper_3c_20t_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fintegral_5fv_3c_20t_20_3e_20_3e_20_3e_276',['SerializeHelper&lt; T, std::enable_if_t&lt; std::is_integral_v&lt; T &gt; &gt; &gt;',['../structsupermap_1_1io_1_1SerializeHelper_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__integral__v_3_01T_01_4_01_4_01_4.html',1,'supermap::io']]],
  ['shallowdeserializedsize_277',['ShallowDeserializedSize',['../structsupermap_1_1io_1_1ShallowDeserializedSize.html',1,'supermap::io']]],
  ['shallowdeserializer_278',['ShallowDeserializer',['../structsupermap_1_1io_1_1ShallowDeserializer.html',1,'supermap::io']]],
  ['shallowdeserializer_3c_20key_3c_20keylen_20_3e_20_3e_279',['ShallowDeserializer&lt; Key&lt; KeyLen &gt; &gt;',['../structsupermap_1_1io_1_1ShallowDeserializer.html',1,'supermap::io']]],
  ['shallowserializer_280',['ShallowSerializer',['../structsupermap_1_1io_1_1ShallowSerializer.html',1,'supermap::io']]],
  ['shallowserializer_3c_20key_3c_20keylen_20_3e_20_3e_281',['ShallowSerializer&lt; Key&lt; KeyLen &gt; &gt;',['../structsupermap_1_1io_1_1ShallowSerializer.html',1,'supermap::io']]],
  ['singlefileindexedstorage_282',['SingleFileIndexedStorage',['../classsupermap_1_1SingleFileIndexedStorage.html',1,'supermap']]],
  ['singlefileindexedstorage_3c_20supermap_3a_3akeyvalue_2c_20indext_2c_20void_20_3e_283',['SingleFileIndexedStorage&lt; supermap::KeyValue, IndexT, void &gt;',['../classsupermap_1_1SingleFileIndexedStorage.html',1,'supermap']]],
  ['sortedsinglefileindexedstorage_284',['SortedSingleFileIndexedStorage',['../classsupermap_1_1SortedSingleFileIndexedStorage.html',1,'supermap']]],
  ['sortedsinglefileindexedstorage_3c_20content_2c_20indext_2c_20typename_20register_3a_3aitemsinfo_2c_20findpattern_20_3e_285',['SortedSingleFileIndexedStorage&lt; Content, IndexT, typename Register::ItemsInfo, FindPattern &gt;',['../classsupermap_1_1SortedSingleFileIndexedStorage.html',1,'supermap']]],
  ['sortedsinglefileindexedstorage_3c_20supermap_3a_3akeyvalue_2c_20indext_2c_20void_2c_20supermap_3a_3akey_20_3e_286',['SortedSingleFileIndexedStorage&lt; supermap::KeyValue, IndexT, void, supermap::Key &gt;',['../classsupermap_1_1SortedSingleFileIndexedStorage.html',1,'supermap']]],
  ['sortedstorageslist_287',['SortedStoragesList',['../classsupermap_1_1SortedStoragesList.html',1,'supermap']]],
  ['sortedstorageslist_3c_20t_2c_20indext_2c_20innerregisterinfo_2c_20findpatterntype_20_3e_288',['SortedStoragesList&lt; T, IndexT, InnerRegisterInfo, FindPatternType &gt;',['../classsupermap_1_1SortedStoragesList.html',1,'supermap']]],
  ['storageitemregister_289',['StorageItemRegister',['../classsupermap_1_1StorageItemRegister.html',1,'supermap']]],
  ['storageitemregister_3c_20filtertoadd_2c_20std_3a_3ashared_5fptr_3c_20filter_3c_20filtertoadd_2c_20filtertocontain_20_3e_20_3e_20_3e_290',['StorageItemRegister&lt; FilterToAdd, std::shared_ptr&lt; Filter&lt; FilterToAdd, FilterToContain &gt; &gt; &gt;',['../classsupermap_1_1StorageItemRegister.html',1,'supermap']]],
  ['storageitemregister_3c_20t_2c_20countingstorageinfo_3c_20indext_2c_20additionalinfo_20_3e_20_3e_291',['StorageItemRegister&lt; T, CountingStorageInfo&lt; IndexT, AdditionalInfo &gt; &gt;',['../classsupermap_1_1StorageItemRegister.html',1,'supermap']]],
  ['storageitemregister_3c_20t_2c_20void_20_3e_292',['StorageItemRegister&lt; T, void &gt;',['../classsupermap_1_1StorageItemRegister.html',1,'supermap']]],
  ['storagevalueignorer_293',['StorageValueIgnorer',['../structsupermap_1_1StorageValueIgnorer.html',1,'supermap']]],
  ['stringinputstream_294',['StringInputStream',['../classsupermap_1_1io_1_1StringInputStream.html',1,'supermap::io']]],
  ['stringoutputstream_295',['StringOutputStream',['../classsupermap_1_1io_1_1StringOutputStream.html',1,'supermap::io']]],
  ['supermap_296',['Supermap',['../classsupermap_1_1Supermap.html',1,'supermap']]],
  ['supermapbuilder_297',['SupermapBuilder',['../classsupermap_1_1detail_1_1SupermapBuilder.html',1,'supermap::detail']]],
  ['supermapexception_298',['SupermapException',['../classsupermap_1_1SupermapException.html',1,'supermap']]]
];
